ALTER TABLE clientes ADD COLUMN cidade VARCHAR(100);
ALTER TABLE clientes ADD COLUMN uf VARCHAR(2);
ALTER TABLE clientes ADD COLUMN numero VARCHAR(100);
ALTER TABLE clientes ADD COLUMN complemento VARCHAR(100);
